import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
// https://flowbite.com/blocks/marketing/header/#default-header-navigation
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
    <html lang="en">
      <body className={inter.className}>
      <div>
        {children}</div>
      </body>
    </html>
  )
}

// <script src="flowbite.min.js"></script>
